---

image: centos:7

before_script:
  - yum -y remove docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-engine && yum -y install -y yum-utils device-mapper-persistent-data lvm2
  - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - yum check-update && yum -y update && yum -y install docker-ce docker-ce-cli containerd.io python gcc python-devel curl
  - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" && python get-pip.py
  - pip install pip setuptools -U && pip install --ignore-installed molecule molecule[docker]
  - ls -la

test:
  stage: test
    script:
    - molecule test
